Bootstrap switch on system with Docker
* Functional should be moved into fuel-bootstrap util
Partially implements: blueprint dynamically-build-bootstrap
Change-Id: If9289dbedd568f316d1731437ffa3ab82d7cf7c2

diff --git a/fuel-bootstrap-image-builder/bin/fuel-bootstrap-image-set b/fuel-bootstrap-image-builder/bin/fuel-bootstrap-image-set
--- a/fuel-bootstrap-image-builder/bin/fuel-bootstrap-image-set
+++ b/fuel-bootstrap-image-builder/bin/fuel-bootstrap-image-set
@@ -6,8 +6,8 @@ MYSELF="${0##*/}"
 ASTUTE_YAML="/etc/fuel/astute.yaml"
 cobbler_manifest="/etc/puppet/modules/nailgun/examples/cobbler-only.pp"
 astute_manifest="/etc/puppet/modules/nailgun/examples/astute-only.pp"
-ubuntu_bootstrap_dir="/var/www/nailgun/bootstrap/ubuntu"
-bootstrap_conf="/etc/fuel-bootstrap-image.conf"
+#ubuntu_bootstrap_dir="/var/www/nailgun/bootstrap/ubuntu"
+#bootstrap_conf="/etc/fuel-bootstrap-image.conf"
 
 run_puppet () {
 	local container="$1"
@@ -30,30 +30,31 @@ run_puppet () {
 
 maybe_build_ubuntu_bootstrap ()
 {
-	local log='/var/log/fuel-bootstrap-image-build.log'
-	local need_rebuild=''
-	for item in linux initramfs.img root.squashfs; do
-		if [ ! -f "$ubuntu_bootstrap_dir/$item" ]; then
-			need_rebuild='yes'
-		fi
-	done
-	if ! grep -qE '^\s*BOOTSTRAP_SSH_KEYS\s*[=]' "$bootstrap_conf" 2>/dev/null; then
-		echo >> "$bootstrap_conf"
-		echo "BOOTSTRAP_SSH_KEYS=\"/root/.ssh/id_rsa.pub\"" >> "$bootstrap_conf"
-	fi
-	if [ -n "$need_rebuild" ]; then
-		cat >&2 <<-EOF
-		$MYSELF: info: Ubuntu bootstrap image does not exist, building one
-		$MYSELF: info: build log is available at $log
-		EOF
-		if ! fuel-bootstrap-image >>"$log" 2>&1; then
-			cat >&2 <<-EOF
-			$MYSELF: error: failed to build Ubuntu bootstrap image
-			$MYSELF: error: see $log for more details
-			EOF
-			exit 1
-		fi
-	fi
+        echo "Activating ubuntu bootstrap"
+#	local log='/var/log/fuel-bootstrap-image-build.log'
+#	local need_rebuild=''
+#	for item in linux initramfs.img root.squashfs; do
+#		if [ ! -f "$ubuntu_bootstrap_dir/$item" ]; then
+#			need_rebuild='yes'
+#		fi
+#	done
+#	if ! grep -qE '^\s*BOOTSTRAP_SSH_KEYS\s*[=]' "$bootstrap_conf" 2>/dev/null; then
+#		echo >> "$bootstrap_conf"
+#		echo "BOOTSTRAP_SSH_KEYS=\"/root/.ssh/id_rsa.pub\"" >> "$bootstrap_conf"
+#	fi
+#	if [ -n "$need_rebuild" ]; then
+#		cat >&2 <<-EOF
+#		$MYSELF: info: Ubuntu bootstrap image does not exist, building one
+#		$MYSELF: info: build log is available at $log
+#		EOF
+#		if ! fuel-bootstrap-image >>"$log" 2>&1; then
+#			cat >&2 <<-EOF
+#			$MYSELF: error: failed to build Ubuntu bootstrap image
+#			$MYSELF: error: see $log for more details
+#			EOF
+#			exit 1
+#		fi
+#	fi
 }
 
 maybe_restart_dnsmasq () {
@@ -77,10 +78,6 @@ verify_bootstrap_flavor () {
 			;;
 		ubuntu|Ubuntu)
 			flavor='ubuntu'
-			cat >&2 <<-EOF
-			$MYSELF: WARNING: Ubuntu based bootstrap is EXPERIMENTAL.
-			$MYSELF: WARNING: Use at your own risk.
-			EOF
 			;;
 		*)
 			cat >&2 <<-EOF
